# Generated by Django 4.2.30 on 2026-04-14 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '활성'), ('cancelled', '해지'), ('expired', '만료')], default='active', max_length=10, verbose_name='상태')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='시작일')),
                ('expires_at', models.DateTimeField(verbose_name='만료일')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='해지일')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='plans.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '구독',
                'verbose_name_plural': '구독',
                'db_table': 'subscriptions',
            },
        ),
    ]
