# Generated by Django 4.2.30 on 2026-04-14 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='주문 ID')),
                ('amount', models.PositiveIntegerField(verbose_name='결제 금액')),
                ('status', models.CharField(choices=[('pending', '대기'), ('done', '완료'), ('failed', '실패'), ('cancelled', '취소')], default='pending', max_length=10, verbose_name='상태')),
                ('toss_payment_key', models.CharField(blank=True, max_length=200, verbose_name='토스 paymentKey')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='결제 완료 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '결제',
                'verbose_name_plural': '결제',
                'db_table': 'payments',
            },
        ),
    ]
