# Generated by Django 4.2.30 on 2026-04-14 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='플랜명')),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20, verbose_name='티어')),
                ('billing_cycle', models.CharField(choices=[('monthly', '월간'), ('yearly', '연간')], default='monthly', max_length=10, verbose_name='결제 주기')),
                ('price', models.PositiveIntegerField(verbose_name='가격 (원)')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='vendors.vendor')),
            ],
            options={
                'verbose_name': '플랜',
                'verbose_name_plural': '플랜',
                'db_table': 'plans',
            },
        ),
    ]
