# Generated by Django 4.2.30 on 2026-04-14 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='플랫폼 수수료 비율', max_digits=5, verbose_name='수수료율 (%)')),
                ('effective_date', models.DateField(help_text='이 날짜부터 적용되는 수수료율', verbose_name='적용 시작일')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_rates', to='vendors.vendor')),
            ],
            options={
                'verbose_name': '정산율',
                'verbose_name_plural': '정산율',
                'db_table': 'settlement_rates',
                'ordering': ['-effective_date'],
                'unique_together': {('vendor', 'effective_date')},
            },
        ),
        migrations.CreateModel(
            name='SettlementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='정산 시작일')),
                ('period_end', models.DateField(verbose_name='정산 종료일')),
                ('status', models.CharField(choices=[('SUCCESS', '성공'), ('FAILED', '실패')], default='FAILED', max_length=10)),
                ('expected_settlements', models.IntegerField(default=0, verbose_name='예상 정산 건수')),
                ('actual_settlements', models.IntegerField(default=0, verbose_name='실제 정산 건수')),
                ('expected_user_settlements', models.IntegerField(default=0, verbose_name='예상 유저 정산 건수')),
                ('actual_user_settlements', models.IntegerField(default=0, verbose_name='실제 유저 정산 건수')),
                ('total_commission', models.PositiveIntegerField(default=0, verbose_name='총 수수료')),
                ('is_verified', models.BooleanField(default=False, help_text='예상값과 실제값이 일치하는지 여부', verbose_name='정합성 검증 통과')),
                ('processed_seconds', models.FloatField(blank=True, null=True, verbose_name='처리 소요시간(초)')),
                ('error_message', models.TextField(blank=True, verbose_name='에러 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '정산 실행 이력',
                'verbose_name_plural': '정산 실행 이력',
                'db_table': 'settlement_histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='정산 시작일')),
                ('period_end', models.DateField(verbose_name='정산 종료일')),
                ('total_sales', models.PositiveIntegerField(default=0, verbose_name='총 매출')),
                ('commission', models.PositiveIntegerField(default=0, verbose_name='수수료')),
                ('payout_amount', models.PositiveIntegerField(default=0, verbose_name='정산 금액')),
                ('status', models.CharField(choices=[('pending', '정산 대기'), ('completed', '정산 완료')], default='pending', max_length=10, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='정산 완료일')),
                ('settlement_rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='settlements.settlementrate', verbose_name='적용된 정산율')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='vendors.vendor')),
            ],
            options={
                'verbose_name': '정산',
                'verbose_name_plural': '정산',
                'db_table': 'settlements',
                'ordering': ['-period_start'],
                'unique_together': {('vendor', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='UserSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='결제 금액')),
                ('commission', models.PositiveIntegerField(verbose_name='수수료')),
                ('payout', models.PositiveIntegerField(verbose_name='정산 금액')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_settlements', to='payments.payment')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_settlements', to='settlements.settlement')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '유저별 정산',
                'verbose_name_plural': '유저별 정산',
                'db_table': 'user_settlements',
                'unique_together': {('settlement', 'payment')},
            },
        ),
    ]
