# Generated by Django 4.2.30 on 2026-04-14 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='회사명')),
                ('business_number', models.CharField(max_length=20, verbose_name='사업자등록번호')),
                ('status', models.CharField(choices=[('pending', '승인 대기'), ('approved', '승인'), ('rejected', '거절')], default='pending', max_length=10, verbose_name='승인 상태')),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='수수료율 (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '벤더',
                'verbose_name_plural': '벤더',
                'db_table': 'vendors',
            },
        ),
    ]
